spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/shopping
    username: root
    password: 123456789
#hikari:
      ##      maximum-pool-size: 100
      ##      minimum-idle: 10
      ##      idle-timeout: 30000
    ##      max-lifetime: 1200000
    ##      connection-timeout: 20000
#  shardingsphere:
#    # 数据源相关配置
#    datasource:
#      # 数据源名称
#      names: master,s1,s2
#      # MySQL master数据源
#      master:
#        # 数据库连接池
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: org.mariadb.jdbc.Driver
#        jdbc-url: jdbc:mysql://127.0.0.1:3307/icrown1?autoReconnect=true&validConnectionTimeout=20&connectTimeout=25&useServerPrepStmts=true
#        username: root
#        password: 123456789
#        pool-name: HikariPool-1
#        maximum-pool-size: 100
#        minimum-idle: 50
#        idle-timeout: 30000
#        max-lifetime: 1200000
#        connection-timeout: 20000
    #      # 两个slave数据源
    #      s1:
    #        type: com.zaxxer.hikari.HikariDataSource
    #        driver-class-name: org.mariadb.jdbc.Driver
    #        jdbc-url: jdbc:mysql://192.168.5.205:3306/icrown1?autoReconnect=true&validConnectionTimeout=20&connectTimeout=25&useServerPrepStmts=true
    #        username: root
    #        password: 1qaz@WSX
    #        pool-name: HikariPool-1
    #        maximum-pool-size: 100
    #        minimum-idle: 50
    #        idle-timeout: 30000
    #        max-lifetime: 1200000
    #        connection-timeout: 20000
    #      s2:
    #        type: com.zaxxer.hikari.HikariDataSource
    #        driver-class-name: org.mariadb.jdbc.Driver
    #        jdbc-url: jdbc:mysql://192.168.5.206:3306/icrown1?autoReconnect=true&validConnectionTimeout=20&connectTimeout=25&useServerPrepStmts=true
    #        username: root
    #        password: 1qaz@WSX
    #        pool-name: HikariPool-1
    #        maximum-pool-size: 100
    #        minimum-idle: 50
    #        idle-timeout: 30000
    #        max-lifetime: 1200000
    #        connection-timeout: 20000
    #    masterslave:
    #      load-balance-algorithm-type: round_robin
    #      name: ms
    #      master-data-source-name: master
    #      slave-data-source-names: s1,s2
    # 其他属性
    props:
      # 开启SQL显示
      sql.show: true

    jackson:
      time-zone: Asia/Taipei
